# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: manimax3
email: manimax3@hotmail.de

#write html inside the double quotes to display in jumbotron
description: "<h3>Devlogs about my projects and more...</h3>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manimax3.github.io" # the base hostname & protocol for your site
twitter_username: manimax3
github_username:  manimax3

# Build settings
markdown: kramdown
future: false
show_drafts: false
